basePath: /api/v1
definitions:
  common.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.CreateQueueRequest:
    properties:
      description:
        type: string
      eventTime:
        type: string
      location:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  models.Queue:
    properties:
      activeCashierIds:
        items:
          type: string
        type: array
      closureReason:
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      description:
        type: string
      eventTime:
        type: string
      id:
        type: string
      location:
        type: string
      mentorIds:
        items:
          type: string
        type: array
      name:
        type: string
      status:
        description: 'active, closed, ... // FIXME: enum?'
        type: string
    type: object
host: https://ezq.onrender.com
info:
  contact: {}
  description: Queue service API
  title: Easy Queue API
  version: "1.0"
paths:
  /queues:
    post:
      consumes:
      - application/json
      description: Create a new queue
      parameters:
      - description: Queue payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateQueueRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Queue'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Create queue
      tags:
      - queues
swagger: "2.0"
